configs:
  params:
    server.insecure: true
  
  cm:
    admin.enabled: true
    url: http://localhost:8080
    accounts.admin: apiKey
    dex.config: |
      connectors:
        - type: github
          id: github
          name: GitHub
          config:
            clientID: Ov23li7L6oRuONdBgiR1
            clientSecret: 1d24290df1f11b29f910bb692344cdea6dad2628
            redirectURI: http://localhost:8080/api/dex/callback
  
  rbac:
    # match by github username using preferred_username
    scopes: '[groups, preferred_username]'
    policy.default: 'role:readonly'
    policy.csv: |
      p, role:admin, applications, *, */*, allow
      g, mogaal, role:admin
      g, jaacu, role:admin
      g, eddymdz, role:admin
      g, pabloberrettoni, role:admin
      g, ricardocamacho, role:admin
      g, joseluiscodesk8, role:admin
